CREATE DATABASE IF NOT EXISTS postdb;

USE postdb;
CREATE TABLE IF NOT EXISTS post (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(500) NOT NULL,
content VARCHAR(5000) NOT NULL,
upvotes INT,
downvotes INT,
createdtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

USE postdb;
CREATE TABLE IF NOT EXISTS  ips (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ip VARCHAR(5000) NOT NULL
);

DELIMITER $$
DROP TRIGGER IF EXISTS tg_post_insert $$
CREATE TRIGGER tg_post_insert BEFORE INSERT ON post
FOR EACH ROW
BEGIN
  SET NEW.upvotes = IFNULL(NEW.upvotes, 0);
  SET NEW.downvotes = IFNULL(NEW.downvotes, 0);
END $$
DELIMITER ;